'use strict';
const { Router } = require('express');
const authorize = require('../../core/middleware/authorize');
const validate = require('../../core/middleware/validateRequest');
const { managers } = require('../../core/security/employeeAccess');
const roles = require('../../core/constants/roles');
const v = require('./attendance.validation');
const createController = require('./attendance.controller');
module.exports = function createAttendanceRouter({ authenticate, service } = {}) {
  if (typeof authenticate !== 'function') throw new TypeError('Attendance routes require shared authenticate middleware.');
  const router = Router();
  const controller = createController(service);
  const id = validate(req => v.id(req.params.id));
  router.use(authenticate);
  router.get('/attendance/me', authorize('EMPLOYEE'), validate(req => v.listQuery(req.query, true)), controller.mine);
  router.post('/attendance/check-in', authorize('EMPLOYEE'), validate(req => v.empty(req.body)), controller.checkIn);
  router.post('/attendance/check-out', authorize('EMPLOYEE'), validate(req => v.checkoutInput(req.body)), controller.checkOut);
  router.get('/attendance', authorize(...managers), validate(req => v.listQuery(req.query)), controller.list);
  router.post('/attendance', authorize(...managers), validate(req => v.manualInput(req.body)), controller.create);
  router.get('/attendance/:id', authorize(...Object.values(roles)), id, controller.get);
  router.patch('/attendance/:id', authorize(...managers), id, validate(req => v.manualInput(req.body, true)), controller.correct);
  return router;
};
